version: 2

sources:
  - name: raw
    schema: public
    tables:
      - name: telegram_messages
        description: "Raw Telegram message data"
        freshness:
          warn_after: { count: 24, period: hour }
          error_after: { count: 48, period: hour }
        loaded_at_field: (message_json->>'date')  # or your actual timestamp column
