# File Path: docker-compose.yml
# Date: 10 July 2025
# Developed by: Addisu Taye Dadi
# Purpose: Orchestrate multiple services (PostgreSQL and Python app).
# Key Features:
# - Starts PostgreSQL DB and mounts it as a service.
# - Loads environment variables from .env file.

version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: