version: 1

models:
  - name: dim_dates
    description: "Date dimension table used for time-based analysis"
    columns:
      - name: date
        description: "Full date key used for joining with fact tables"
        tests:
          - unique
          - not_null
      - name: year
        description: "Year part of the date"
      - name: month
        description: "Month number (1-12)"
      - name: is_weekend
        description: "Boolean indicating if the date falls on a weekend"