version: 1

sources:
  - name: raw
    description: "Raw JSON files from Telegram scraping"
    tables:
      - name: telegram_messages
        description: "Raw unprocessed Telegram messages stored as JSON"

models:
  - name: stg_telegram_messages
    description: "Cleaned and lightly transformed Telegram messages"
    columns:
      - name: message_id
        description: "Unique identifier for each message"
      - name: message_text
        description: "Text content of the message"
      - name: message_date
        description: "Date the message was posted"

  - name: dim_channels
    description: "Dimension table listing all scraped Telegram channels"
    columns:
      - name: channel_id
        description: "Surrogate key for each channel"
      - name: channel_name
        description: "Name of the Telegram channel"

  - name: fct_messages
    description: "Fact table linking messages to channels and dates"
    columns:
      - name: message_id
        description: "Foreign key to message"
      - name: channel_id
        description: "Foreign key to dimension channel table"